CREATE TABLE public.cats
(
    catname character varying NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    catage integer NOT NULL,
    catgender character varying NOT NULL,
    catbreed character varying,
    CONSTRAINT cats_pkey PRIMARY KEY (id)
)